FROM python:3.9.18-slim

# Set the working directory
WORKDIR /mlflow

# Install MLflow
RUN pip install mlflow

# Set up the SQLite database URI as an environment variable

# Expose the port the app runs on
EXPOSE 5000

# Command to run the MLflow server
CMD mlflow ui -h 0.0.0.0
